---
- hosts: all
  tasks:
    - name: install epel repo
      yum:
        name: epel-release
        state: latest
    - name: install the latest version of nginx
      yum:
        name: nginx
        state: latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: index.html
      copy:
        dest: "/usr/share/nginx/html/index.html"
        content: "{{ ansible_hostname }}\n"
